version: '3'

services: 
    # Database
    db:
        container_name: ${APP_NAME}-db
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - wpsite
    # phpmyadmin
    phpmyadmin:
        depends_on: 
            - db
        container_name: ${APP_NAME}-phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '${PHPMYADMIN_PORT}:80'
        environment: 
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks: 
            - wpsite
    # Wordpress
    wordpress:
        build: ./docker/wordpress
        depends_on: 
            - db
        container_name: ${APP_NAME}-wordpress
        ports:
            - '${WORDPRESS_PORT}:80'
        restart: always
        volumes: 
            - ./:/var/www/html
            - ./docker/dev.ini:/usr/local/etc/php/conf.d/dev.ini
        environment: 
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD} 
        networks: 
            - wpsite
    # mailhog
    mailhog:
       container_name: ${APP_NAME}-mailhog
       image: 'mailhog/mailhog:latest'
       restart: always
       ports:
           - '1025:1025'
           - '8025:8025'
       networks: 
           - wpsite
networks: 
    wpsite:
volumes:
    db_data:
