version: '3.9'

services: 
    # Database
    db:
        image: mysql:5.7
        volumes:
            - ./db_data:/var/lib/mysql
        restart: "no"
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - wpsite
    # phpmyadmin
    phpmyadmin:
        depends_on: 
            - db
        image: phpmyadmin/phpmyadmin
        restart: "no"
        ports:
            - '${PHPMYADMIN_PORT}:80'
        environment: 
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks: 
            - wpsite
    # Wordpress
    wordpress:
        depends_on: 
            - db
        build: ./docker/wordpress
        ports:
            - '${WORDPRESS_PORT}:80'
        volumes: 
            - ./src:/var/www/html:rw,cached
            - ./docker/dev.ini:/usr/local/etc/php/conf.d/dev.ini
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD} 
        networks: 
            - wpsite
    # mailhog
    mailhog:
        image: 'mailhog/mailhog:latest'
        restart: "no"
        ports:
            - '1025:1025'
            - '8025:8025'
        networks: 
            - wpsite
    #nginx
    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        restart: "no"
        volumes:
            - ./docker/nginx/templates:/etc/nginx/templates
            - ./docker/nginx/certs:/etc/nginx/certs
            - ./docker/nginx/log:/var/log/nginx
            - ./src:/var/www/html:rw,cached
        environment:
            - "DOMAIN=${DOMAIN}"
        depends_on:
            - wordpress
        networks:
            - wpsite
networks: 
    wpsite: